spring:

  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/reception?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.2.42:1521:ORCL
    username: test_gs
    password: test_gs
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis
  redis:
    host: localhost
    port: 6379
  http: 
    multipart: 
      maxFileSize: 10MB  
      maxRequestSize: 10MB 
      location: D:\local\ #windows格式 
      #location: /app/tmp  linux格式 
# 分页配置
pagehelper:
  helper-dialect: mysql  #指定分页插件使用方言
  offsetAsPageNum: true #当该参数设置为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数分页
  rowBoundsWithCount: true #当该参数设置为true时，使用 RowBounds 分页会进行 count 查询
  pageSizeZero: true #当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  reasonable: true  #当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页
  autoRuntimeDialect: true  #根据多数据源自动识别对应方言的分页
  closeConn: true #默认true关闭，设置为 false 后，不会关闭获取的连接
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql #为了支持startPage(Object params)方法

server:
  port: 8088
  context-path: /ReceptionMS
debug: false
#logging:
#  file: D:\spring\ResourceCatalog\logs\ResourceCatalog-${server.port}.log
  
photoPath: E:/Workspaces/MyEclipse 2017/ReceptionMS/src/main/webapp/views/upload/imgs/photo/
filePath: E:\\
